#!/bin/sh
set -e

case "$1" in
purge)
	if command -v deb-systemd-helper >/dev/null 2>&1; then
		deb-systemd-helper purge prometheus-jbod-exporter.service >/dev/null || true
		deb-systemd-helper unmask prometheus-jbod-exporter.service >/dev/null || true
	fi
	rm -f /etc/default/prometheus-jbod-exporter
	;;
remove)
	if command -v deb-systemd-helper >/dev/null 2>&1; then
		deb-systemd-helper mask prometheus-jbod-exporter.service >/dev/null || true
	fi
	;;
esac

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi

exit 0
